### PR TITLE
Frontend improvements for match rescheduling

### PR DESCRIPTION
**Pull request by robigan**
PR to support custom schedules instead of the automatic ones.

Discussed in #519

### CODE REVIEW

**Comment by robigan** [comment]
I have just realized, there already is a match component. With the custom duration built in.
Mfw
Bruh

**Comment by robigan** [comment]
Actually I should so some testing but I gtg

**Comment by robigan** [comment]
@evroon We have our UI setup like this, but I saw that you made a change where onClick of the schedule row's card it opens the update model. I feel like the whole tap a card thing to open is more of a mobile thing, and on desktop isn't clear that it can be clicked, plus the drag mouse UI doesn't help either to indicate it is clickable. You introduced the change in https://github.com/evroon/bracket/commit/24f04fbaa0f1aafe59e44ca53a0b378705507296

image

**Comment by evroon** [comment]
I'm not sure I understand what this PR does. What problem does this PR solve exactly? I guess what it does is allow you to enter a datetime instead of margins/durations, but what is the use case it targets?

**Comment by robigan** [comment]
> > @evroon We have our UI setup like this, but I saw that you made a change where onClick of the schedule row's card it opens the update model. I feel like the whole tap a card thing to open is more of a mobile thing, and on desktop isn't clear that it can be clicked, plus the drag mouse UI doesn't help either to indicate it is clickable. You introduced the change in [24f04fb](https://github.com/evroon/bracket/commit/24f04fbaa0f1aafe59e44ca53a0b378705507296)
> > image
> 
> Hmm how would you improve it? Have some kind of button like the green pencil one in your screenshot that opens the modal?

Yup, we had this same UI problem with the old schedule page, I see you've removed. It just wasn't clear to our tournament staff they had to click to edit the match

**Comment by robigan** [comment]
> I'm not sure I understand what this PR does. What problem does this PR solve exactly? I guess what it does is allow you to enter a datetime instead of margins/durations, but what is the use case it targets?

Originally, there was no proper way to edit the custom duration/delay fields of matches, nor was it intuitive, and our staff thought that they had to do it from the planning page. And aimed to add that functionality, this PR now basically adds some QoL features such as having functionality to calculate the delay required if you want the next match to start at a certain time, and adding that button to hint to the user they can actually edit the card. In terms of DX, I also added some typings pertaining the parts of code I touched but I could add more typings

**Comment by robigan** [comment]
Oh, and cleaned up some typings and added some code optimizations.

**Comment by robigan** [comment]
Gotta still test some things, this isn't exactly merge ready

**Comment by robigan** [comment]
Actually yeah the rest of the type system is complaining, I might might just type everything

**Comment by robigan** [comment]
@evroon ?

**Comment by evroon** [comment]
I like the typing improvements.

Regarding the functionality changes, I'm less sure. For now, tournaments in bracket happen on one date, so showing the date doesn't really have added value right? 

But I'm still not very sure what this PR adds exactly, [here](https://github.com/evroon/bracket/pull/530/files#diff-f0273b3be3c068fc376e3d1caad84d3400859651baedf71899baead4c78edcb1R232-R288) for example.

**Pull request closed without merging**
