### PR TITLE
Fix backend to recalculate start time on match update

### PR DESCRIPTION
**Pull request by robigan**

### CODE REVIEW

**Comment by robigan** [comment]
Yes github bot I'm aware, also being away from the machine with all the necessary changes is hard too

**Comment by robigan** [comment]
Got round to testing, not sure why this shouldn't work

**Comment by robigan** [comment]
Well, I should say that it's been working in production for us for a long while, I haven't tested on a local machine but I'm pretty sure it's been working very reliably for long. Shall I attempt to add a test for this @evroon ?
image

**Comment by evroon** [comment]
If you could add a test, that would be nice indeed!

**Comment by robigan** [comment]
> If you could add a test, that would be nice indeed!

"100% of diff hit" according to CodeCov, so there you have it 👍

**Comment by robigan** [comment]
@evroon ?

**Comment by evroon** [comment]
Sorry for the delay, thanks for fixing this bug!

**Pull request merged**
