### PR TITLE
Rank by points

### PR DESCRIPTION
**Pull request by IzStriker**
Partially addresses #524
When choosing teams from a previous stage, teams can now either be ranked by the highest elo or the highest amount of points accumulated across matches.

### CODE REVIEW

**Comment by evroon** [comment]
Thanks for the PR, I hope to be able to look at it in a few days

**Comment by evroon** [comment]
Hmm I looked at it but I am not sure this is the way to go. I would prefer something more flexible, like how other tournament systems have a scoring system. 

There you can kind of "design" your scoring, and specify how much `game_points` a `win` attributes to for example.

So what I think we want is a table of scorings, and each row in that table contains settings as to how the scoring works. So how many points are awarded per win and per tie for example. Most tournaments will just use one kind of scoring. Later we can extend this system to also take into account scoring for forfeits, "bye"s, scoring of sets within matches etc. It also lets you define tie-breaking criteria, but that can wait for another time.

There's also two things that are currently a bit of a mistake in my implementation:
- we don't keep track of a team's (or player's) score within a stage item, which is essential to calculate the score correctly
- "Number of teams advancing from the previous stage" should probably instead be "Number of teams advancing to the next stage", that makes more sense. 

Sorry I didn't come up with this earlier. What do you think of this approach?

**Comment by IzStriker** [comment]
> Hmm I looked at it but I am not sure this is the way to go. I would prefer something more flexible, like how other tournament systems have a scoring system.
> 
> There you can kind of "design" your scoring, and specify how much `game_points` a `win` attributes to for example.
> 
> So what I think we want is a table of scorings, and each row in that table contains settings as to how the scoring works. So how many points are awarded per win and per tie for example. Most tournaments will just use one kind of scoring. Later we can extend this system to also take into account scoring for forfeits, "bye"s, scoring of sets within matches etc. It also lets you define tie-breaking criteria, but that can wait for another time.
> 
> There's also two things that are currently a bit of a mistake in my implementation:
> 
> * we don't keep track of a team's (or player's) score within a stage item, which is essential to calculate the score correctly
> * "Number of teams advancing from the previous stage" should probably instead be "Number of teams advancing to the next stage", that makes more sense.
> 
> Sorry I didn't come up with this earlier. What do you think of this approach?

I think understand what you're suggesting. However, I implemented the scoring system in this PR because it's the system my local club uses to score tournaments.  I don't think I could achieve the same system with what you're describing unless I am misunderstanding.

**Comment by evroon** [comment]
I'm working on a draft here: https://github.com/evroon/bracket/pull/797

Ah I think I understand now what you mean why it wouldn't work. It's because you add the number of points in the match as ranking, not the result of the match (win or loss). I should be able to implement that in my PR. If you want to write code, I can also skip that part (but make it easy to implement) and let you do that.

**Comment by IzStriker** [comment]
I'm not fused about writing code, but let me know if you want help with anything. Also, if you don't need this PR feel free to close it. 🙂

**Comment by evroon** [comment]
I have implemented my idea in https://github.com/evroon/bracket/pull/797, with support (from what I understand) for your use case. There is a checkbox you can check when creating a ranking to enable adding the score to the amount of points of a team.

So then I'll close this RP, if something is missing, feel free to create an issue and I'll see if I can add it.

Thanks for all the effort anyway!

**Pull request closed without merging**
