### PR TITLE
Add multi-architecture build support to GitHub Actions

### PR DESCRIPTION
**Pull request by BachErik**
Extend the Docker publishing workflow to build and push images for both amd64 and arm64 architectures using Docker Buildx.

### CODE REVIEW

**Comment by BachErik** [comment]
would fix: #649

**Comment by evroon** [comment]
That's great, thanks!

**Comment by evroon** [comment]
Ah, there is something wrong with it though, I think you do need QEMU: https://github.com/evroon/bracket/actions/runs/10090192217/job/27899100775

**Comment by BachErik** [comment]
Then we would have the following problem:
https://github.com/BachErik/bracket/actions/runs/10090374375/job/27899663426

**Comment by BachErik** [comment]
The `node:18-alpine` image is incompatible with `linux/arm64/v8` only with `linux/arm/v6`, `linux/arm/v7`, `linux/arm64`. (`linux/amd64`, `linux/ppc64le`, `linux/s390x`)

**Comment by evroon** [comment]
@BachErik I got it working now fo `linux/arm64/v8` with node 22

https://github.com/evroon/bracket/actions/runs/13291607490/job/37113550755?pr=1120

**Pull request merged**
